---
# Rule descriptions:
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

default: true

MD003:  # Heading style
  style: atx
MD004:  # Unordered list style
  style: dash
MD009:  # Trailing spaces
  strict: true  # Hard-break 2 spaces must cause a line break
MD013:  # Line length
  code_blocks: false
  stern: true
  tables: false
MD035:  # Horizontal rule
  style: "---"
MD046:  # Code block style
  style: fenced
MD048:  # Code fence style
  style: backtick
MD049:  # Emphasis style
  style: asterisk
MD050:  # Strong style
  style: asterisk
