# https://docs.mergify.com/


pull_request_rules:
  - name: Automatic merge PRs from trusted contributors + Automatic merge on approval
    conditions: []
    actions:
      queue:
queue_rules:
  - name: duplicated default from Automatic merge PRs from trusted contributors
    queue_conditions:
      - base=main
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      # List the required status checks
      - status-success=CI Workflow - Success
      - "#approved-reviews-by>=1"
      - or:
          - author=JohnStrunk
          - author=renovate-bot  # Renovate bot - dependency updates
    merge_conditions: []
    merge_method: merge
  - name: default
    # These queue rules are also applied to all pull requests that funnel to
    # this queue.
    queue_conditions:
      - base=main
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      # List the required status checks
      - status-success=CI Workflow - Success
      - "#approved-reviews-by>=1"
    merge_conditions: []
    merge_method: merge
